#!/usr/bin/env bash
#
#    chargen
#    Author- wbc
#    Creation Date- Sun Aug 05 2018
###########################################################
##    First line of script description
##    Second line of script description
##    Third line of script description
###########################################################
##    First script objective
##    Second script objective
##    Third script objective
###########################################################
##    Color Variables
###########################################################
#
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
CYAN=`tput setaf 6`
LTRED=`tput setaf 9`
LTGRN=`tput setaf 10`
LTYLLW=`tput setaf 11`
LTBLU=`tput setaf 12`
LTMAG=`tput setaf 13`
LTCYN=`tput setaf 14`
BOLD=`tput bold`
RESET=`tput sgr0`
#
###########################################################
##    Script Options/Usage
###########################################################
#
usage () {
    cat <<END

Put Usage & Options here
Requires argument Character Main name (One word- NO spaces
This will also be the name of you generated character sheet
That will be placed in your user's \$HOME dirctory.

END
}
#
[[ $1 ]] || { usage; exit 1; }
###########################################################
##    Global Variables and Information Gathering
###########################################################
##    Comment 1 - what why
CHARNAM="$1"
CHARSHT="${CHARNAM}.csv"
FILDIR="${HOME}"
##    Comment 2 - how
###########################################################
##    Environmental Variables and Conditional Logic
###########################################################
##    Comment 1 - what why
##    Comment 2 - how
###########################################################
##    Declare Functions
###########################################################
##    Comment 1 - what why
##    Comment 2 - how
###########################################################
##    Execution - CleanUp - Exit/Status
###########################################################
##    Comment 1 - what why
read -p "Enter your character's full name, leave blank to use ${CHARNAM}...
" CHARFULNAM
[[ ! $CHARFULNAM ]] && CHARFULNAM="${CHARNAM}"
echo -e "Your Name is $CHARFULNAM"
read -p "Enter your character's Class/s- If multi-class then separate with a / NO Spaces...
" CHARCLASS
echo -e "Your Class is $CHARCLASS"
read -p "Enter your character's Class-Level/s- If multi-class then separate with a / NO Spaces...
" CHARLVL
echo -e "Your Level/s is $CHARLVL"

##    Comment 2 - how
#
