#!/bin/bash
#
####    lastvice
####    Author- Shawn Miller
####    Friday 15 February 2018
#
###########################################################
##    Global Variables and Information Gathering
###########################################################
#
PROGNAME=$(basename $0)
PROGVERS="1.0.1-08"
PROGDATE="2018-02-16"
#
###########################################
####    Declare Color Variables
###########################################
#
RED="$(tput setaf 1)"
GRN="$(tput setaf 2)"
YLLW="$(tput setaf 3)"
BLU="$(tput setaf 4)"
MAG="$(tput setaf 5)"
CYN="$(tput setaf 6)"
LTRED="$(tput setaf 9)"
LTGRN="$(tput setaf 10)"
LTYLLW="$(tput setaf 11)"
LTBLU="$(tput setaf 12)"
LTMAG="$(tput setaf 13)"
LTCYN="$(tput setaf 14)"
BGBLU="$(tput setab 4)"
BGYLLW="$(tput setab 3)"
BGLYLLW="$(tput setab 11)"
ULINE="$(tput smul)"
NULINE="$(tput rmul)"
SOMODE="$(tput smso)"
NSOMODE="$(tput rmso)"
BOLD="$(tput bold)"
RESET="$(tput sgr0)"
#
###########################################################
##    Script Options/Usage
###########################################################
#
usage () {
    clear
    cat <<EOT
${BOLD}${YLLW}Description-${RESET}${LTCYN}
  I started this script shortly after I quit smoking cigarettes and I wanted to keep up with how many
  days it had been, everything was 'hard-coded' with my own info. I realized that this could be used
  for anyone and any bad habit or vice that had been broken. (I had smoked for 37 years)${BOLD}${YLLW}
Parameters-${RESET}${LTCYN}
    ${ULINE}OPTION          ${GRN}Description      ${YLLW}Long Description                                     ${NULINE}${RESET}${LTCYN}
    [${YLLW}<yourname>${LTCYN}]${GRN}    Your Name${YLLW}        Your name as the ${BOLD}${ULINE}${LTCYN}FIRST${NULINE}${RESET}${YLLW} argument, as${LTCYN} Shawn${YLLW} or${LTCYN} "Shawn Miller"${LTCYN}
    [${YLLW}<quitdate>${LTCYN}]${GRN}    Quit Date${YLLW}        Your quit date as the ${BOLD}${ULINE}${LTCYN}SECOND${NULINE}${RESET}${YLLW} argument, as${BOLD}${LTCYN} YYYY-MM-DD${RESET}${LTCYN}
    [${YLLW}<yourvice>${LTCYN}]${GRN}    Your Vice${YLLW}        Your Vice as the ${BOLD}${ULINE}${LTCYN}THIRD${NULINE}${RESET}${YLLW} argument, as${LTCYN} drinking${YLLW} or${LTCYN} "drinking soda"${YLLW}${LTYLLW}
  ${ULINE}Optional${NULINE}-${RESET}${LTYLLW} The following arguments are optional${LTCYN}
    [months]${GRN}        Number Months${LTRED}    (Option In-Progress...)${LTCYN}
    [years]${GRN}         Number Years${LTRED}     (Option In-Progress...)${LTCYN}
    [help]${GRN}          Help${YLLW}             Show this output and exit${LTCYN}
    []${GRN}              Same as Help${YLLW}     Show this output and exit${BOLD}${YLLW}
Usage-${RESET}${GRN}
    ./${PROGNAME}${LTCYN} [OPTION] [${YLLW}<YourName>${LTCYN}|"${YLLW}<Your Name>${LTCYN}"] [${YLLW}<YYYY-MM-DD>${LTCYN}] ["${YLLW}<Your Vice>${LTCYN}"] [months|years]${LTYLLW} 
  Examples-${GRN}
    ./$PROGNAME Shawn 2018-11-19 "a cigarette!"
    ./$PROGNAME "Shawn Miller" 2018-11-19 "Drinking Dr. Pepper!"
    ./$PROGNAME "Shawn Miller" 2018-11-19 "a cigarette!!!" months${LTYLLW}
  Output Number of Days- ${BOLD}${RED}0-89${YLLW} 90-179${GRN} 180+ (flashing)${RESET}${YLLW}
Feedback, Questions, Bugs- ${LTBLU}seaphor@woodbeeco.com${YLLW}
Github-${LTBLU} https://github.com/SeaPhor${RESET}
EOT
}
#
###########################################
####    Declare Arg Checks
###########################################
#
[[ $@ =~ "help" ]] && { usage; exit 0; }
[[ ! $2 ]] && { usage; exit 1; }
[[ ! $1 ]] && { usage; exit 1; }
[[ ! $3 ]] && { usage; exit 1; }
if [[ "`echo $3`" != "" ]]; then
    if [[ $(echo $3) == "months" ]]; then
        usage
        exit 1
    elif [[ $(echo $3) == "years" ]]; then
        usage
        exit 1
    else
        mywhat=$3
    fi
else
    usage
    exit 1
fi
[[ $@ =~ "months" ]] && months=true || months=false
[[ $@ =~ "years" ]] && months=true || years=false
#
###########################################
####    Environment Variables and Information Gathering
###########################################
#
declare -i numdays=$(echo $((($(date +%s --date $quitdate)-$(date +%s))/(3600*24))) | sed 's/[^0-9]//g')
if [[ $numdays -ge 180 ]]; then
    allrt_clr="${BOLD}${GRN}${SOMODE}${ULINE}"
else
    if [[ $numdays -le "89" ]]; then
        allrt_clr="${BOLD}${RED}${ULINE}"
    else
        allrt_clr="${BOLD}${YLLW}${ULINE}"
    fi
fi
#
[[ $months ]] && numonths=$((($numdays)/(30)))
[[ $years ]] && numyears=$((($numdays)/(365)))
#[[ $months ]] && numonths="$(expr $numdays '/' 30)"
#[[ $years ]] && numyears="$(expr $numdays '/' 365)"
#
###########################################
####    Declare Functions
###########################################
#
norm_print () {
echo -e "\n${BOLD}${GRN}${quitter}${RESET}${YLLW} has gone${BOLD}${CYN} =====>>>>>  ${allrt_clr}${numdays}${NULINE}${NSOMODE}${RESET}${BOLD}${CYN}  <<<<<===== ${RESET}${LTYLLW}Days without ${mywhat}\n${RESET}"
}
#
so_print () {
echo -e "\n${SOMODE}${BOLD}${GRN}${quitter}${RESET}${SOMODE}${YLLW} has gone${BOLD}${CYN} =====>>>>>  ${allrt_clr}${numdays}${NULINE}${RESET}${SOMODE}${BOLD}${CYN}  <<<<<===== ${RESET}${SOMODE}${LTYLLW}Days without ${mywhat}\n${NSOMODE}${RESET}"
}
#
declare -i times=10
declare -i count=0
if [[ $numdays -ge 180 ]]; then
    until (( times == count )); do
        clear
        norm_print
        sleep .5
        clear
        so_print
        sleep .5
        ((++count))
    done
else
    norm_print
fi
#
if $months; then
    echo -e "${BOLD}${allrt_clr}${numonths} Months\n${RESET}"
fi
if $years; then
    echo -e "${BOLD}${allrt_clr}${numyears} Years\n${RESET}"
fi
#
exit 0
#
####    Reference: https://linuxconfig.org/how-to-count-days-since-a-specific-date-until-today-using-bash-shell
#
